var sTreeFlatSWD = {
	"id":"cp",
	"cat":"cp",
	"children":
		[
			{
				"id":"tp",
				"cat":"xp",
				"children":
					[
						{
							"id":"vp",
							"cat":"xp",
							"children":
								[
									{
										"id":"showed_0",
										"cat":"x0"
									},
									{
										"id":"IndirectObj",
										"cat":"xp",
										"children":
											[
												{
													"id":"workers_1",
													"cat":"x0"
												}
											]
									},
									{
										"id":"DirectObj",
										"cat":"xp",
										"children":
											[
												{
													"id":"dog_2",
													"cat":"x0"
												}
											]
									}
								]
						}
					]
			},
		]
	
};