/*
TABLE OF CONTENTS
Line 9: trees with no adjuncts
Line 118: trees with adjuncts; all XP segments visible
Line 263: trees with adjuncts; higher XP segments visible, lower XP segments invisible
Line 408: trees with adjuncts; lower XP segments visible, higher XP segments invisible
*/

//Trees with no adjuncts. Used by all systems.

var sTreeNV = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"NP",
				"cat":"xp",
				"children":
					[
						{
							"id":"workers_0",
							"cat":"x0"
						}
					]
			},
			{
				"id":"Tbar",
				"cat":"xbar",
				"children":
					[
						{
							"id":"T",
							"cat":"x0",
							"silent":true
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"helped_1",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

var sTreeVNN = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"T",
				"cat":"x0",
				"silent":true
			},
			{
				"id":"vP",
				"cat":"xp",
				"children":
					[
						{
							"id":"show_0",
							"cat":"x0"
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"NP-IO",
										"cat":"xp",
										"children":
											[
												{
													"id":"workers_1",
													"cat":"x0"
												}
											]
									},
									{
										"id":"Vbar",
										"cat":"xbar",
										"children":
											[
												{
													"id":"Vtrace",
													"cat":"trace",
													"silent":true
												},
												{
													"id":"NP-DO",
													"cat":"xp",
													"children":
														[
															{
																"id":"dog_2",
																"cat":"x0"
															}
														]
												}
											]
									}
								]
						}
					]
			}
		]
};

//Trees with adjuncts. All XP segments visible.

var sTreeNAV_HL = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"NP1",
				"cat":"xp",
				"children":
					[
						{
							"id":"NP2",
							"cat":"xp",
							"children":
								[
									{
										"id":"workers_0",
										"cat":"x0"
									}
								]
						},
						{
							"id":"AP",
							"cat":"xp",
							"children":
								[
									{
										"id":"mature_1",
										"cat":"x0"
									}
								]
						}
					]
			},
			{
				"id":"Tbar",
				"cat":"xbar",
				"children":
					[
						{
							"id":"T",
							"cat":"x0",
							"silent":true
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"helped_2",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

var sTreeVNNAdv_HL = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"T",
				"cat":"x0",
				"silent":true
			},
			{
				"id":"vP1",
				"cat":"xp",
				"children":
					[
						{
							"id":"vP2",
							"cat":"xp",
							"children":
								[
									{
										"id":"give_0",
										"cat":"x0"
									},
									{
										"id":"VP",
										"cat":"xp",
										"children":
											[
												{
													"id":"NP-IO",
													"cat":"xp",
													"children":
														[
															{
																"id":"worker_1",
																"cat":"x0"
															}
														]
												},
												{
													"id":"Vbar",
													"cat":"xbar",
													"children":
														[
															{
																"id":"Vtrace",
																"cat":"trace",
																"silent":true
															},
															{
																"id":"NP-DO",
																"cat":"xp",
																"children":
																	[
																		{
																			"id":"chair_2",
																			"cat":"x0"
																		}
																	]
															}
														]
												}
											]
									}
								]
						},
						{
							"id":"AdvP",
							"cat":"xp",
							"children":
								[
									{
										"id":"slowly_3",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

//Trees with adjuncts. Higher XP segments visible, lower XP segments invisible.

var sTreeNAV_H = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"NP1",
				"cat":"xp",
				"children":
					[
						{
							"id":"NP2",
							"cat":"invisible",
							"children":
								[
									{
										"id":"workers_0",
										"cat":"x0"
									}
								]
						},
						{
							"id":"AP",
							"cat":"xp",
							"children":
								[
									{
										"id":"mature_1",
										"cat":"x0"
									}
								]
						}
					]
			},
			{
				"id":"Tbar",
				"cat":"xbar",
				"children":
					[
						{
							"id":"T",
							"cat":"x0",
							"silent":true
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"helped_2",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

var sTreeVNNAdv_H = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"T",
				"cat":"x0",
				"silent":true
			},
			{
				"id":"vP1",
				"cat":"xp",
				"children":
					[
						{
							"id":"vP2",
							"cat":"invisible",
							"children":
								[
									{
										"id":"give_0",
										"cat":"x0"
									},
									{
										"id":"VP",
										"cat":"xp",
										"children":
											[
												{
													"id":"NP-IO",
													"cat":"xp",
													"children":
														[
															{
																"id":"worker_1",
																"cat":"x0"
															}
														]
												},
												{
													"id":"Vbar",
													"cat":"xbar",
													"children":
														[
															{
																"id":"Vtrace",
																"cat":"trace",
																"silent":true
															},
															{
																"id":"NP-DO",
																"cat":"xp",
																"children":
																	[
																		{
																			"id":"chair_2",
																			"cat":"x0"
																		}
																	]
															}
														]
												}
											]
									}
								]
						},
						{
							"id":"AdvP",
							"cat":"xp",
							"children":
								[
									{
										"id":"slowly_3",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

//Trees with adjuncts. Lower XP segments visible, higher XP segments invisible.

var sTreeNAV_L = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"NP1",
				"cat":"invisible",
				"children":
					[
						{
							"id":"NP2",
							"cat":"xp",
							"children":
								[
									{
										"id":"workers_0",
										"cat":"x0"
									}
								]
						},
						{
							"id":"AP",
							"cat":"invisible",
							"children":
								[
									{
										"id":"mature_1",
										"cat":"x0"
									}
								]
						}
					]
			},
			{
				"id":"Tbar",
				"cat":"xbar",
				"children":
					[
						{
							"id":"T",
							"cat":"x0",
							"silent":true
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"helped_2",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

var sTreeVNNAdv_L = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"T",
				"cat":"x0",
				"silent":true
			},
			{
				"id":"vP1",
				"cat":"invisible",
				"children":
					[
						{
							"id":"vP2",
							"cat":"xp",
							"children":
								[
									{
										"id":"give_0",
										"cat":"x0"
									},
									{
										"id":"VP",
										"cat":"xp",
										"children":
											[
												{
													"id":"NP-IO",
													"cat":"xp",
													"children":
														[
															{
																"id":"worker_1",
																"cat":"x0"
															}
														]
												},
												{
													"id":"Vbar",
													"cat":"xbar",
													"children":
														[
															{
																"id":"Vtrace",
																"cat":"trace",
																"silent":true
															},
															{
																"id":"NP-DO",
																"cat":"xp",
																"children":
																	[
																		{
																			"id":"chair_2",
																			"cat":"x0"
																		}
																	]
															}
														]
												}
											]
									}
								]
						},
						{
							"id":"AdvP",
							"cat":"xp",
							"children":
								[
									{
										"id":"slowly_3",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

kinyamboTreesNoAdjuncts = [sTreeNV, sTreeVNN];
kinyamboTrees_HLvisible = kinyamboTreesNoAdjuncts.concat([sTreeNAV_HL, sTreeVNNAdv_HL]);
kinyamboTrees_Lvisible = kinyamboTreesNoAdjuncts.concat([sTreeNAV_L, sTreeVNNAdv_L]);
kinyamboTrees_Hvisible = kinyamboTreesNoAdjuncts.concat([sTreeNAV_H, sTreeVNNAdv_H]);
