/* What counts for Match? 
	- only the highest XP-segs
	- APs/AdvPs
*/

//Tree (1) in pdf: "Workers helped."
var sTreeNV_ignoreLowerXPsegs = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"NP",
				"cat":"xp",
				"children":
					[
						{
							"id":"workers_0",
							"cat":"x0"
						}
					]
			},
			{
				"id":"Tbar",
				"cat":"xbar",
				"children":
					[
						{
							"id":"T",
							"cat":"x0",
							"silent":true
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"helped_1",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

//Tree 2 in pdf: "workers mature helped"
var sTreeNAV_ignoreLowerXPsegs = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"NP1",
				"cat":"xp",
				"children":
					[
						{
							"id":"NP2",
							"cat":"invisibleseg",
							"children":
								[
									{
										"id":"workers_0",
										"cat":"x0"
									}
								]
						},
						{
							"id":"AP",
							"cat":"xp",
							"children":
								[
									{
										"id":"mature_1",
										"cat":"x0"
									}
								]
						}
					]
			},
			{
				"id":"Tbar",
				"cat":"xbar",
				"children":
					[
						{
							"id":"T",
							"cat":"x0",
							"silent":true
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"helped_2",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

//Tree 3 in pdf: "show workers dog"
var sTreeVNN_ignoreLowerXPsegs = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"T",
				"cat":"x0",
				"silent":true
			},
			{
				"id":"vP",
				"cat":"xp",
				"children":
					[
						{
							"id":"show_0",
							"cat":"x0"
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"NP-IO",
										"cat":"xp",
										"children":
											[
												{
													"id":"workers_1",
													"cat":"x0"
												}
											]
									},
									{
										"id":"Vbar",
										"cat":"xbar",
										"children":
											[
												{
													"id":"Vtrace",
													"cat":"trace",
													"silent":true
												},
												{
													"id":"NP-DO",
													"cat":"xp",
													"children":
														[
															{
																"id":"dog_2",
																"cat":"x0"
															}
														]
												}
											]
									}
								]
						}
					]
			}
		]
};

//Tree 4 in pdf: "show chief of-workers dog"
var sTreeVNNN_ignoreLowerXPsegs = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"T",
				"cat":"x0",
				"silent":true
			},
			{
				"id":"vP",
				"cat":"xp",
				"children":
					[
						{
							"id":"show_0",
							"cat":"x0"
						},
						{
							"id":"VP",
							"cat":"xp",
							"children":
								[
									{
										"id":"NP-IO",
										"cat":"xp",
										"children":
											[
												{
													"id":"chief_1",
													"cat":"x0"
												},
												{
													"id":"NP-gen",
													"cat":"xp",
													"children":
														[
															{
																"id":"of-workers_2",
																"cat":"x0"
															}
														]
												}
											]
									},
									{
										"id":"Vbar",
										"cat":"xbar",
										"children":
											[
												{
													"id":"Vtrace",
													"cat":"trace",
													"silent":true
												},
												{
													"id":"NP-DO",
													"cat":"xp",
													"children":
														[
															{
																"id":"dog_3",
																"cat":"x0"
															}
														]
												}
											]
									}
								]
						}
					]
			}
		]
};

//Tree 5 in pdf: "give worker chair slowly"
var sTreeVNNAdv_ignoreLowerXPsegs = {
	"id":"TP",
	"cat":"xp",
	"children":
		[
			{
				"id":"T",
				"cat":"x0",
				"silent":true
			},
			{
				"id":"vP1",
				"cat":"xp",
				"children":
					[
						{
							"id":"vP2",
							"cat":"invisibleseg",
							"children":
								[
									{
										"id":"give_0",
										"cat":"x0"
									},
									{
										"id":"VP",
										"cat":"xp",
										"children":
											[
												{
													"id":"NP-IO",
													"cat":"xp",
													"children":
														[
															{
																"id":"worker_1",
																"cat":"x0"
															}
														]
												},
												{
													"id":"Vbar",
													"cat":"xbar",
													"children":
														[
															{
																"id":"Vtrace",
																"cat":"trace",
																"silent":true
															},
															{
																"id":"NP-DO",
																"cat":"xp",
																"children":
																	[
																		{
																			"id":"chair_2",
																			"cat":"x0"
																		}
																	]
															}
														]
												}
											]
									}
								]
						},
						{
							"id":"AdvP",
							"cat":"xp",
							"children":
								[
									{
										"id":"slowly_3",
										"cat":"x0"
									}
								]
						}
					]
			}
		]
};

var kinyamboTrees_ignoreLowerXPsegs = ['sTreeNV_ignoreLowerXPsegs', 'sTreeNAV_ignoreLowerXPsegs', 'sTreeVNN_ignoreLowerXPsegs', 'sTreeVNNN_ignoreLowerXPsegs', 'sTreeVNNAdv_ignoreLowerXPsegs'];