name: test-spot-frontend
on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install mocha #global
      #test with run: mocha first to check if mocha can be used
      - run: npm install chai
      - run: sudo apt install google-chrome-stable
      - run: npm install selenium-webdriver
      - run: npm install -g chromedriver 
      - run: ./mochaBuild.sh #inside of mochaBuild.sh create new script that builds frontend tests
      - run: npm run test2 #inside of test2 being mocha test should run selenium file
      #have to create selenium file and run that file with npm
    
 
