name: test-spot-frontend
on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install mocha #global
      #test with run: mocha first to check if mocha can be used
      - run: npm install chai
      - run: sudo apt-get install firefox
      - run: npm install selenium-webdriver
      - run: install -g firefoxdriver
      - run: ./mochaBuild.sh
      - run: npm test
 
