name: test-spot-frontend
on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i mocha-headless-chrome
      - run: npm install chai
      - run: ./mochaBuild.sh #inside of mochaBuild.sh create new script that builds frontend tests
      - run: npm run test_frontend
    
 
